---
title: "The effect of COVID-19 pandemic on Croatian tourist sector"
author: "Bogdan, S., Sikic, L. and Suzana,XXX"
date: '`r format(Sys.time(), "%d %B, %Y")`'
header-includes:
  - \usepackage{caption}
  - \captionsetup[figure]{labelformat=empty}
output:
  bookdown::tufte_html2:
    number_sections: no
    toc: yes
  bookdown::pdf_document2:
    includes:
      before_body:
      in_header: preamble.tex
    keep_tex: yes
    latex_engine: xelatex
    number_sections: true
    toc: no
  bookdown::word_document2: null 
bibliography: "D:/LUKA/Academic/Covid-vs-Tourism/Literatura/reference.bib"
fontsize: 12pt
link-citations: yes
---



```{r library, warning=FALSE, include=FALSE}

library(estudy2)
library(plotly)
library(TSstudio)
library(jsonlite)
library(plyr)
library(zoo)
library(httr)
library(plotly)
library(jsonlite)
library(dplyr)
library(tidyr)
library(Quandl)
library(stringr)
library(eventstudies)
        
```



# INTRODUCTION

# RESEARCH BACKGROUND AND CONTEXT 

# DATA COLLECTION AND METHODOLOGY

```{r importData, echo=FALSE,  message = FALSE, warning = FALSE}

ISIN <- readxl::read_xlsx("./Data/ISIN_list.xlsx") %>% select(ISIN) 

links <- c()
rawDta <- c()
for( i in ISIN){ 
  links <- paste0('https://zse.hr/json/securityHistory/', i,
                  '/2019-01-01/2021-04-13/hr?trading_model_id=ALL')
}
for (i in links){
rawDta[[i]] <- fromJSON(content(GET(i), as = "text", encoding = "UTF-8")) 
}

stockDF <- lapply(rawDta, '[[', "rows") %>% bind_rows()


source("./Secret/Passkey.R")
Crobex <- Quandl("ZAGREBSE/CROBEX", type = "zoo",collapse = "daily",start_date = "2019-01-02", end_date = Sys.Date())
gold <- Quandl("LBMA/GOLD", type = "zoo", collapse = "daily", start_date = "2019-01-01",end_date = Sys.Date())
gold <- gold[,5]

```

```{r cleanData, echo=FALSE,  message = FALSE, warning = FALSE}

TOURISMdta <- stockDF %>% select(Date = date, Close = last_price, url) %>%
  mutate(Date = gsub("[.]$","", Date)) %>%
  mutate(Ticker = str_sub(.$url,-37,-34)) %>%
  mutate(Close = as.numeric(gsub("(.*),.*", "\\1", Close))) %>%
  select(-url) %>%
  group_by(Ticker) %>%
  mutate(n = n()) %>%
  ungroup() %>% 
  filter(n > 100) %>%
  select(-n) %>%
  group_by(Ticker) %>%
  distinct(Date, .keep_all=TRUE) %>%
  ungroup() %>%
  tidyr::spread(Ticker, Close, fill=0) %>%
  mutate( Date = as.Date(Date,"%d.%m.%Y")) %>%
  arrange(desc(Date))


TOURISMdta <- zoo(TOURISMdta[,-1], order.by = TOURISMdta$Date)


```

```{r stockReturns, echo=FALSE, message=FALSE, warning=FALSE}
rates <- get_rates_from_prices(TOURISMdta,
                               quote = "Close",
                               multi_day = TRUE,
                               compounding = "continuous")

ratesDF <- data.frame(Date = rownames(ratesDF), rates) %>% mutate(Date = as.Date(Date,"%Y-%m-%d"))
rownames(ratesDF) <- NULL

ratesDF[sapply(ratesDF, is.infinite)] <- NA
ratesDF[sapply(ratesDF, is.nan)] <- NA
ratesDF[sapply(ratesDF, is.na)] <- 0


rates <-  zoo(ratesDF[,-1], order.by = ratesDF$Date)
```

```{r crobexReturn, echo=FALSE, message=FALSE, warning=FALSE}
rates_indx <- get_rates_from_prices(Crobex, 
                                    quote = "Close",
                                    multi_day = TRUE,
                                    compounding = "continuous")

colnames(rates_indx) <- "Crobex"
```

```{r goldReturn, echo=FALSE, message=FALSE, warning=FALSE}
add_indx <- get_rates_from_prices(gold, 
                                  quote = "Close",
                                  multi_day = TRUE,
                                  compounding = "continuous")

colnames(add_indx) <- "gold"
```

## Methodology


## Insigthts from the data and topic identification

 


# RESULTS AND DISCUSSION


## Nonparametric tests

```{r, echo=FALSE, message=FALSE, warning=FALSE}
securities_returns <- apply_market_model(
  rates = rates,
  regressor = rates_indx,
  same_regressor_for_all = TRUE,
  market_model = "sim",
  estimation_method = "ols",
  estimation_start = as.Date("2019-01-01"),
  estimation_end = as.Date("2020-01-23")
)

parametric_tests(list_of_returns = securities_returns,
                 event_start = as.Date("2020-02-24"),
                 event_end = as.Date("2020-04-14"))
```




## Parametric tests

```{r, echo=FALSE, message=FALSE, warning=FALSE}
nonparametric_tests(list_of_returns = securities_returns,
                    event_start = as.Date("2020-02-24"),
                    event_end = as.Date("2020-04-14"))
```


## Visual presentation of results


```{r vizNOexter, echo=FALSE, message=FALSE, warning=FALSE}
SplitD <- data.frame(name=colnames(rates),
                     when = rep(as.Date("2020-02-24"),12))

Returns <- na.omit(rates)

es <- eventstudy(firm.returns = Returns,
                 event.list = SplitD,
                 event.window = 40,
                 type = "None",
                 to.remap = TRUE,
                 remap = "cumsum",
                 inference = TRUE,
                 inference.strategy = "bootstrap")

plot(es)
```

```{r vizNOexter, echo=FALSE, message=FALSE, warning=FALSE}
es2 <- eventstudy(firm.returns = Returns,
                 event.list = SplitD,
                 event.window = 40,
                 type = "marketModel",
                 to.remap = TRUE,
                 remap = "cumsum",
                 inference = TRUE,
                 inference.strategy = "bootstrap",
                 model.args = list(market.returns=rates_indx$Crobex))

plot(es2)
```



# CONCLUSION

# BIBLIOGRAPHY




